name: Bug Report
about: Create a report to help us improve

title: "[Bug] "

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        **Description**

        [Provide a brief description of the issue.]

        **Steps to Reproduce**

        1. [Step 1]
        2. [Step 2]
        3. ...

        **Expected Behavior**

        [Describe what you expected to happen.]

        **Actual Behavior**

        [Describe what actually happened.]

        **Environment**

        - **SonarGit Version**: [Specify the version]
        - **Node.js Version**: [Specify the version]
        - **Operating System**: [Specify the OS, e.g., Windows, macOS, Linux]

        **Screenshots**

        [If applicable, include screenshots that help illustrate the issue.]

        **Additional Information**

        [Any additional information, logs, or context that might be helpful in understanding and resolving the issue.]

        ---

        **Note:**
        - Please make sure to search for existing issues before creating a new one.
        - Follow the issue template to help us better understand and address the problem.
        - Be respectful and provide as much detail as possible to facilitate a quicker resolution.
