name: Publish to npm

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Extract the tag version
          VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')

          # Log in to npm
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

          # Publish to npm
          npm version "$VERSION" --allow-same-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
